export enum GameState {
  LOBBY = 'LOBBY',
  WAITING_FOR_PLAYERS = 'WAITING_FOR_PLAYERS',
  DAY_DISCUSSION = 'DAY_DISCUSSION',
  DAY_SPEECHES = 'DAY_SPEECHES',
  DAY_VOTING = 'DAY_VOTING',
  VOTE_RESULTS = 'VOTE_RESULTS',
  NIGHT_MAFIA = 'NIGHT_MAFIA',
  NIGHT_SERIAL = 'NIGHT_SERIAL',
  NIGHT_DOCTOR = 'NIGHT_DOCTOR',
  NIGHT_DETECTIVE = 'NIGHT_DETECTIVE',
  NIGHT_RESOLUTION = 'NIGHT_RESOLUTION',
  GAME_END = 'GAME_END',
}

export enum Team {
  CITIZEN = 'CITIZEN',
  MAFIA = 'MAFIA',
  SOLO = 'SOLO',
}

export enum VotingMode {
  ANONYMOUS = 'ANONYMOUS',
  VISIBLE = 'VISIBLE',
}

export enum ActionType {
  KILL = 'KILL',
  HEAL = 'HEAL',
  CHECK = 'CHECK',
}

export enum ClientType {
  TV = 'TV',
  HOST = 'HOST',
  PLAYER = 'PLAYER',
}

export enum WebSocketEvent {
  // Client to Server
  JOIN_SESSION = 'JOIN_SESSION',
  SELECT_SLOT = 'SELECT_SLOT',
  SUBMIT_VOTE = 'SUBMIT_VOTE',
  SUBMIT_NIGHT_ACTION = 'SUBMIT_NIGHT_ACTION',
  FINISH_SPEAKING = 'FINISH_SPEAKING',
  HEARTBEAT = 'HEARTBEAT',
  
  // Host actions
  START_GAME = 'START_GAME',
  NEXT_PHASE = 'NEXT_PHASE',
  ASSIGN_FOUL = 'ASSIGN_FOUL',
  KICK_PLAYER = 'KICK_PLAYER',
  RESTORE_PLAYER = 'RESTORE_PLAYER',
  UPDATE_CONFIG = 'UPDATE_CONFIG',
  RESTART_GAME = 'RESTART_GAME',
  UNDO_ACTION = 'UNDO_ACTION',
  
  // Server to Clients
  SESSION_STATE_UPDATE = 'SESSION_STATE_UPDATE',
  ROLE_ASSIGNED = 'ROLE_ASSIGNED',
  TIMER_UPDATE = 'TIMER_UPDATE',
  VOTE_PROGRESS = 'VOTE_PROGRESS',
  VOTE_PROGRESS_HOST = 'VOTE_PROGRESS_HOST',
  VOTE_RESULT = 'VOTE_RESULT',
  PLAYER_ELIMINATED = 'PLAYER_ELIMINATED',
  FOUL_ASSIGNED = 'FOUL_ASSIGNED',
  GAME_ENDED = 'GAME_ENDED',
  PLAYER_JOINED = 'PLAYER_JOINED',
  PLAYER_LEFT = 'PLAYER_LEFT',
  ERROR = 'ERROR',
}
